project:
  type: website
  render:
    - index.qmd
    - unidad_i/index.qmd
    - unidad_ii/index.qmd
    - unidad_iii/index.qmd

website:
  title: "ANVIDEA — Material reproducible"
  site-url: "https://Javier-2712.github.io/libro_anvidea/"
  repo-url: "https://github.com/Javier-2712/libro_anvidea"
  repo-actions: [source, issue]
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: unidad_i/index.qmd
        text: Unidad I
      - href: unidad_ii/index.qmd
        text: Unidad II
      - href: unidad_iii/index.qmd
        text: Unidad III
    right:
      - icon: github
        href: "https://github.com/Javier-2712/libro_anvidea"

format:
  html:
    cover-image: Logo_GIEN.png
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true

lang: es

execute:
  freeze: auto
